version: '3.9'

services:
  # Mongodb service
  sentiment:
    build:
      context: .
    container_name: sentiment_container
    image: senti_analyzer:latest
    ports:
      - 5000:5000
    restart: always
